-- Flyway V3 — no-op（保留版本占位）
--
-- 历史背景：
--   本脚本最初用于「老 Hibernate ddl-auto 建表的环境」补齐 trade_item / trade_order
--   的新增列与 edu_* 三张新表。作者错用了 PostgreSQL 风格的
--   `ALTER TABLE ... ADD COLUMN IF NOT EXISTS`，该语法在 MySQL 8.x / 9.x 完全不支持，
--   导致全新环境（campushub 库由 createDatabaseIfNotExist 自动建出）启动时
--   ERROR 1064 (42000) at line 7 of V3__trade_edu.sql，后端 BUILD FAILURE。
--
-- 修复决策：
--   1. 经核对，V1__init_schema.sql 已经包含 V3 想 ALTER / CREATE 的全部对象：
--      - trade_item.{description, price_point, pickup_location_type, pickup_location_detail}
--      - trade_order.{negotiated_price_point, buyer_confirmed, seller_confirmed}
--      - 表 edu_tutor_task / edu_forbidden_word_hit / admin_forbidden_word
--   2. 因此在「严格按 V1→V2→V3→V4→V5 顺序的环境」下，V3 本应 no-op。
--   3. 直接删除 V3 文件会破坏 Flyway 版本链（老环境 schema_history 已有 V3 记录），
--      改为 SELECT 1 占位 + 版本号保留，是对所有环境最稳的方案。
--
-- 升级提示：
--   - 若你本地 schema_history 表里 V3 已有「failed」或「success（旧 checksum）」记录，
--     请执行：cd backend && ./mvnw flyway:repair 后重启后端。
--   - 全新本地环境无需任何额外操作。
--
-- 关联 Bug 记录：docs/P4/bug/何翌闻_2026-05-28.md #2

SELECT 1;
